import { SkillType, TechnologyType, TribeType, UnitType } from "../types";

export const UnitSettings: Record<UnitType, { 
    cost: number; 
    attack: number; 
    movement: number; 
    defense: number; 
    range: number; 
    health?: number;
    upgradeFrom?: UnitType
    veteran?: boolean | true;
    unique?: boolean;
    skills: Set<SkillType>;
    becomes?: UnitType;
    super?: boolean;
}> = {
    [UnitType.None]: {
        cost: -1,
        attack: -1,
        movement: 0,
        defense: 0,
        range: 0,
        health: 1,
        skills: new Set([]),
    },
    [UnitType.Warrior]: {
        cost: 2,
        attack: 2,
        movement: 1,
        defense: 2,
        range: 1,
        health: 10,
        skills: new Set([SkillType.Dash, SkillType.Fortify]),
    },
    [UnitType.Rider]: {
        cost: 3,
        attack: 2,
        movement: 2,
        defense: 1,
        range: 1,
        health: 10,
        skills: new Set([SkillType.Dash, SkillType.Escape, SkillType.Fortify]),
    },
    [UnitType.Knight]: {
        cost: 8,
        attack: 3.5,
        movement: 3,
        defense: 1,
        range: 1,
        health: 10,
        skills: new Set([SkillType.Dash, SkillType.Persist, SkillType.Fortify]),
    },
    [UnitType.Defender]: {
        cost: 3,
        attack: 1,
        movement: 1,
        defense: 3,
        range: 1,
        health: 15,
        skills: new Set([SkillType.Fortify]),
    },
    [UnitType.Catapult]: {
        cost: 8,
        attack: 4,
        movement: 1,
        defense: 0,
        range: 3,
        health: 10,
        skills: new Set([SkillType.Stiff]),
    },
    [UnitType.Archer]: {
        cost: 3,
        health: 10,
        attack: 2,
        movement: 1,
        defense: 1,
        range: 2,
        skills: new Set([SkillType.Dash, SkillType.Fortify]),
    },
    [UnitType.MindBender]: {
        cost: 5,
        health: 10,
        attack: 0,
        movement: 1,
        defense: 1,
        range: 1,
        skills: new Set([SkillType.Heal, SkillType.Convert]),
    },
    [UnitType.Swordsman]: {
        cost: 5,
        health: 15,
        attack: 3,
        movement: 1,
        defense: 3,
        range: 1,
        skills: new Set([SkillType.Dash]),
    },
    [UnitType.Giant]: {
        cost: 10,
        super: true,
        health: 40,
        attack: 5,
        movement: 1,
        defense: 4,
        range: 1,
        skills: new Set([]),
    },    
    [UnitType.Cloak]: {
        cost: 8,
        health: 5,
        attack: 0,
        movement: 2,
        defense: 0.5,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.Hide, SkillType.Infiltrate, SkillType.Dash, SkillType.Scout, SkillType.Creep]),
    },
    [UnitType.Dagger]: {
        cost: 2,
        health: 10,
        attack: 2,
        movement: 1,
        defense: 2,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.Dash, SkillType.Surprise, SkillType.Independent]),
    },
    [UnitType.Pirate]: {
        cost: 2,
        health: 10,
        attack: 2,
        movement: 2,
        defense: 2,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.Carry, SkillType.Float, SkillType.Dash, SkillType.Surprise, SkillType.Independent]),
    },
    [UnitType.Dinghy]: {
        cost: 2,
        health: 5,
        attack: 0,
        movement: 2,
        defense: 0.5,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.Carry, SkillType.Float, SkillType.Hide, SkillType.Infiltrate, SkillType.Dash, SkillType.Scout]),
    },

    // Navy
    [UnitType.Raft]: {
        cost: 0,
        attack: -1,
        movement: 2,
        defense: 2,
        range: 2,
        veteran: false,
        skills: new Set([SkillType.Carry, SkillType.Float]),
    },
    [UnitType.Scout]: {
        cost: 5,
        attack: 2,
        movement: 3,
        defense: 2,
        range: 2,
        veteran: false,
        upgradeFrom: UnitType.Raft,
        skills: new Set([SkillType.Carry, SkillType.Dash, SkillType.Float]),
    },
    [UnitType.Rammer]: {
        upgradeFrom: UnitType.Raft,
        cost: 5,
        attack: 3,
        movement: 3,
        defense: 3,
        range: 1,
        skills: new Set([SkillType.Dash, SkillType.Float, SkillType.Carry]),
    },
    [UnitType.Bomber]: {
        cost: 5,
        attack: 3,
        movement: 2,
        defense: 2,
        range: 3,
        upgradeFrom: UnitType.Raft,
        skills: new Set([SkillType.Carry, SkillType.Float, SkillType.Splash, SkillType.Stiff]),
    },
    [UnitType.Juggernaut]: {
        cost: 10,
        attack: 4,
        movement: 2,
        defense: 4,
        range: 1,
        super: true,
        veteran: false,
        skills: new Set([SkillType.Float, SkillType.Carry, SkillType.Stiff, SkillType.Stomp]),
    },

    // Aquarion
    [UnitType.Crab]: {
        cost: 10,
        super: true,
        health: 40,
        attack: 4,
        movement: 2,
        defense: 5,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.Escape, SkillType.Float]),
    },   
    [UnitType.Amphibian]: {
        cost: 3,
        health: 10,
        attack: 2,
        movement: 2,
        defense: 1,
        range: 1,
        skills: new Set([SkillType.Float, SkillType.Dash, SkillType.Escape, SkillType.Fortify]),
    },
    [UnitType.Tridention]: {
        cost: 8,
        health: 10,
        attack: 2.5,
        movement: 2,
        defense: 1,
        range: 2,
        skills: new Set([SkillType.Float, SkillType.Dash, SkillType.Escape, SkillType.Fortify]),
    },

    // Polaris
    [UnitType.Gaami]: {
        cost: 10,
        super: true,
        health: 30,
        attack: 4,
        movement: 1,
        defense: 3,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.AutoFreeze, SkillType.FreezeArea]),
    },
    [UnitType.Mooni]: {
        veteran: false,
        cost: 5,
        health: 10,
        attack: -1,
        movement: 1,
        defense: 1,
        range: 1, 
        unique: true,
        skills: new Set([SkillType.AutoFreeze, SkillType.Skate]),
    },
    [UnitType.BattleSled]: {
        cost: 5,
        health: 15,
        attack: 3,
        movement: 2,
        defense: 2,
        range: 1, 
        unique: true,
        skills: new Set([SkillType.Dash, SkillType.Escape, SkillType.Skate]),
    },
    [UnitType.IceArcher]: {
        cost: 3,
        health: 10,
        attack: 0.1,
        movement: 1,
        defense: 1,
        range: 2,
        skills: new Set([SkillType.Dash, SkillType.Freeze, SkillType.Fortify]),
    },
    [UnitType.IceFortress]: {
        health: 20,
        cost: 15,
        attack: 4,
        movement: 1,
        defense: 3,
        range: 2,
        veteran: false,
        unique: true,
        skills: new Set([SkillType.Skate, SkillType.Scout]),
    },

    // Cymanti
    [UnitType.Centipede]: {
        cost: 10,
        super: true,
        health: 20,
        attack: 4,
        movement: 2,
        defense: 3,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.Dash, SkillType.Eat, SkillType.Creep]),
    },
    [UnitType.Segment]: {
        cost: -1,
        health: 10,
        attack: 2,
        movement: 1,
        defense: 2,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.Independent, SkillType.Creep, SkillType.Explode]),
    },
    [UnitType.Doomux]: {
        cost: 10,
        health: 20,
        attack: 4,
        movement: 3,
        defense: 2,
        range: 1,
        veteran: true,
        skills: new Set([SkillType.Dash, SkillType.Creep, SkillType.Explode]),
    },
    [UnitType.Shaman]: {
        cost: 10,
        health: 10,
        attack: 1,
        movement: 1,
        defense: 1,
        range: 1,
        veteran: false,
        skills: new Set([SkillType.Convert, SkillType.Boost]),
    },
    [UnitType.Kiton]: {
        cost: 3,
        health: 15,
        attack: 1,
        movement: 1,
        defense: 3,
        range: 1,
        skills: new Set([SkillType.Poison]),
    },
    [UnitType.Hexapod]: {
        cost: 3,
        health: 5,
        attack: 3,
        movement: 2,
        defense: 1,
        range: 1,
        skills: new Set([SkillType.Dash, SkillType.Escape, SkillType.Creep]),
    },
    [UnitType.Raychi]: {
        unique: true,
        cost: 8,
        health: 15,
        attack: 3,
        movement: 3,
        defense: 2,
        range: 1,
        skills: new Set([SkillType.Dash, SkillType.Float, SkillType.Creep, SkillType.Navigate, SkillType.Explode]),
    },
    [UnitType.Phychi]: {
        cost: 3,
        health: 5,
        attack: 1,
        movement: 2,
        defense: 2,
        range: 2,
        veteran: true,
        skills: new Set([SkillType.Dash, SkillType.Fly, SkillType.Poison, SkillType.Surprise]),
    },
    [UnitType.Exida]: {
        cost: 8,
        health: 10,
        attack: 3,
        movement: 1,
        defense: 1,
        range: 3,
        veteran: true,
        skills: new Set([SkillType.Poison, SkillType.Splash]),
    },
    
    // Elyron
    [UnitType.DragonEgg]:   {
        health: 10,
        super: true,
        cost: 10,
        attack: -1,
        movement: 1,
        defense: 2,
        range: 1,
        veteran: false,
        becomes: UnitType.BabyDragon,
        skills: new Set([SkillType.Grow, SkillType.Fortify]),
    },
    [UnitType.BabyDragon]:  {
        super: true,
        health: 15,
        cost: 10,
        attack: 3,
        movement: 2,
        defense: 3,
        range: 1,
        veteran: false,
        becomes: UnitType.FireDragon,
        skills: new Set([SkillType.Grow, SkillType.Dash, SkillType.Fly, SkillType.Escape, SkillType.Scout]),
    },
    [UnitType.FireDragon]:  {
        super: true,
        health: 20,
        cost: 10,
        attack: 4,
        movement: 3,
        defense: 3,
        range: 2,
        veteran: false,
        skills: new Set([SkillType.Dash, SkillType.Fly, SkillType.Splash, SkillType.Scout]),
    },
    [UnitType.Polytaur]: {
        cost: 2,
        health: 15,
        attack: 3,
        movement: 1,
        defense: 1,
        range: 2,
        veteran: false,
        skills: new Set([SkillType.Dash, SkillType.Fortify, SkillType.Independent]),
    },
};

export const UnitUpgradables: [UnitType.Scout, UnitType.Rammer, UnitType.Bomber] = [
    UnitType.Scout, 
    UnitType.Rammer, 
    UnitType.Bomber
];

export const UnitSuperTypes: Record<TribeType.Polaris | TribeType.Aquarion | TribeType.Elyrion | TribeType.Cymanti | TribeType.None, UnitType> = {
    [TribeType.Polaris]: UnitType.Gaami,
    [TribeType.Aquarion]: UnitType.Crab,
    [TribeType.Elyrion]: UnitType.DragonEgg,
    [TribeType.Cymanti]: UnitType.Centipede,
    [TribeType.None]: UnitType.Giant
};

Object.freeze(UnitSettings);
Object.freeze(UnitUpgradables);
Object.freeze(UnitSuperTypes);