#!/bin/bash
# Usage: ./deploy.sh
# You must set RUNPOD_HOST and RUNPOD_PORT env vars, or edit them below.
export RUNPOD_HOST=69.30.85.51
export RUNPOD_PORT=22176

HOST="${RUNPOD_HOST:-}"
PORT="${RUNPOD_PORT:-}"
USER="root"

RUN_BENCHMARK=false

# Check arguments
for arg in "$@"; do
    if [ "$arg" == "-b" ]; then
        RUN_BENCHMARK=true
    fi
done

if [ -z "$HOST" ] || [ -z "$PORT" ]; then
    echo "Usage: export RUNPOD_HOST=x.x.x.x RUNPOD_PORT=xxxxx && ./deploy.sh [-b]"
    echo "  -b: Run benchmark after deployment"
    echo "Or edit this script to set defaults."
    read -p "Enter RunPod IP: " HOST
    read -p "Enter RunPod Port: " PORT
fi

echo "Deploying to $USER@$HOST:$PORT..."

# 0. Bootstrap Remote (Install rsync & create dir)
echo "Bootstrapping remote..."
ssh -p $PORT -i ./polyfish-runpod $USER@$HOST "apt-get update && apt-get install -y rsync && mkdir -p /root/polyfish"

# 1. Sync Files (Exclude artifacts, venv, target)
# We use rsync to push the current folder to /root/polyfish
# Note: Using the key 'polyfish-runpod' generated by user
rsync -avz -e "ssh -p $PORT -i ./polyfish-runpod" \
    --exclude 'target' \
    --exclude '.venv' \
    --exclude '*.safetensors' \
    --exclude '.git' \
    ./ $USER@$HOST:/root/polyfish/

# 2. Run Setup on Remote
echo "Running remote setup..."
ssh -p $PORT -i ./polyfish-runpod $USER@$HOST "cd /root/polyfish && chmod +x remote_setup.sh && ./remote_setup.sh"

# 3. Optional: Run Benchmark
if [ "$RUN_BENCHMARK" = true ]; then
    echo "Running Benchmark..."
    ssh -p $PORT -i ./polyfish-runpod $USER@$HOST "cd /root/polyfish && target/release/benchmark"
else
    echo "Deployment finished."
    echo "To connect: ssh -p $PORT $USER@$HOST"
    echo "To run training: ssh -p $PORT $USER@$HOST 'cd polyfish && ./run_training_loop.sh'"
fi
