#!/bin/bash
# Usage: ./deploy.sh
# You must set RUNPOD_HOST and RUNPOD_PORT env vars, or edit them below.
export RUNPOD_HOST=69.30.85.51
export RUNPOD_PORT=22116

HOST="${RUNPOD_HOST:-}"
PORT="${RUNPOD_PORT:-}"
USER="root"

RUN_BENCHMARK=false
SYNC_ONLY=false

# Check arguments
for arg in "$@"; do
    if [ "$arg" == "-b" ]; then
        RUN_BENCHMARK=true
    fi
    if [ "$arg" == "-s" ]; then
        SYNC_ONLY=true
    fi
done

if [ -z "$HOST" ] || [ -z "$PORT" ]; then
    echo "Usage: export RUNPOD_HOST=x.x.x.x RUNPOD_PORT=xxxxx && ./deploy.sh [-b] [-s]"
    echo "  -b: Run benchmark after deployment"
    echo "  -s: Sync files only (skip setup/build)"
    echo "Or edit this script to set defaults."
    read -p "Enter RunPod IP: " HOST
    read -p "Enter RunPod Port: " PORT
fi

echo "Deploying to $USER@$HOST:$PORT..."

# 0. Bootstrap Remote (Install rsync & create dir)
if [ "$SYNC_ONLY" = false ]; then
    echo "Bootstrapping remote..."
    ssh -p $PORT -i ./polyfish-runpod $USER@$HOST "apt-get update && apt-get install -y rsync && mkdir -p /workspace/polyfish"
fi

# 1. Sync Files (Exclude artifacts, venv, target)
# We use rsync to push the current folder to /root/polyfish
# Note: Using the key 'polyfish-runpod' generated by user
rsync -avz --no-o --no-g -e "ssh -p $PORT -i ./polyfish-runpod" \
    --exclude 'target' \
    --exclude '.venv' \
    --exclude '*.safetensors' \
    --exclude '.git' \
    ./ $USER@$HOST:/workspace/polyfish/

# 2. Run Setup on Remote
if [ "$SYNC_ONLY" = false ]; then
    echo "Running remote setup..."
    ssh -p $PORT -i ./polyfish-runpod $USER@$HOST "cd /workspace/polyfish && chmod +x remote_setup.sh && ./remote_setup.sh"
else
    echo "Skipping Remote Setup (Sync Only)"
fi

# 3. Optional: Run Benchmark
if [ "$RUN_BENCHMARK" = true ]; then
    echo "Running Benchmark..."
    ssh -p $PORT -i ./polyfish-runpod $USER@$HOST "cd /workspace/polyfish && target/release/benchmark"
else
    echo "Deployment finished."
    echo "To connect: ssh -p $PORT $USER@$HOST"
    echo "To run training: ssh -p $PORT $USER@$HOST 'cd /workspace/polyfish && ./run_training_loop.sh'"
fi
