CONFIG_MODULE_SIG=n
CONFIG_MODULE_SIG_ALL=n

obj-m += polyai.o

KDIR := /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

all:
	make -C $(KDIR) M=$(PWD) modules

clean:
	make -C $(KDIR) M=$(PWD) clean