#!/usr/bin/env python3
"""Publish the live self-play config so a remote worker mirrors it exactly.

Reads the running self_play process's argv — the authoritative source for
EFF_ITER and every label-shaping flag (value_trust ramp, anchor decay, td_w) —
and writes a shell-sourceable manifest. Deriving EFF_ITER independently would
mean re-implementing run_training_loop.sh's games-scaled schedule and
ITER_OFFSET; reading the live argv can't drift from it.
"""
import json
import os
import struct
import subprocess
import sys

OUT = sys.argv[1] if len(sys.argv) > 1 else "worker/manifest.env"

# Flags the worker sets from its own hardware or that make no sense remotely
# (league --opponent games are the main box's evaluation duty). Everything
# else is forwarded verbatim, so flags added later propagate for free.
DROP_WITH_VALUE = {
    "--num-games", "--actors", "--eval-servers", "--opponent",
    "--eval-backend", "--max-batch", "--coalesce-timeout-us", "--leaf-batch",
}


def live_argv():
    ps = subprocess.run(["ps", "-Ao", "args="], capture_output=True, text=True).stdout
    for line in ps.splitlines():
        if "self_play" in line and "--num-games" in line and "grep" not in line:
            return line.strip().split()
    return None


def strip_local_flags(argv):
    out, i = [], 1  # argv[0] is the binary path
    while i < len(argv):
        if argv[i] in DROP_WITH_VALUE:
            i += 2
            continue
        out.append(argv[i])
        i += 1
    return out


def conv1_in(path):
    """Input-channel count straight from the safetensors header (no torch dep)."""
    try:
        with open(path, "rb") as f:
            n = struct.unpack("<Q", f.read(8))[0]
            header = json.loads(f.read(n))
    except Exception:
        return ""
    for key, meta in header.items():
        if key.endswith("conv1.weight"):
            return meta["shape"][1]
    return ""


def git_sha():
    r = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else ""


def main():
    argv = live_argv()
    if argv is None:
        # Main box is between self_play runs (training/league phase). Leaving
        # the previous manifest in place keeps the worker on the last known
        # config — at most one iteration stale, which is normal off-policy lag.
        print("no live self_play; keeping existing manifest", file=sys.stderr)
        return 0

    args = strip_local_flags(argv)
    iteration = ""
    if "--iteration" in args:
        iteration = args[args.index("--iteration") + 1]

    os.makedirs(os.path.dirname(OUT) or ".", exist_ok=True)
    tmp = OUT + ".tmp"
    with open(tmp, "w") as f:
        f.write("# generated by worker/publish_manifest.py — do not edit\n")
        f.write(f"ITERATION={iteration}\n")
        f.write(f"GIT_SHA={git_sha()}\n")
        f.write(f"CONV1_IN={conv1_in('model.safetensors')}\n")
        f.write("SELF_PLAY_ARGS='" + " ".join(args) + "'\n")
    os.replace(tmp, OUT)
    print(f"manifest: iteration={iteration} args={' '.join(args)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
